#!/bin/bash
cat /etc/passwd/etc/hosts

~
~
~
~
~
~
~
~
~
~
~


~
~
~
~
~
~
~
~
~
~
~
~
~
~
~
~
~
~
~
~
~
~
~
~
~
~
~
~
~
~
-- INSERT --                                                                                                                                                      2,1           All

~
~
~
~
~
~
~
~
~
~
~


